project:
  type: website
  output-dir: "build/html/"

website:
  title: "Epiworld Forecasts"
  navbar:
    left:
      - href: index.qmd
        text: Weekly COVID-19 Forecast
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
