project:
  type: website
  output-dir: "build/html/"

website:
  title: "Epiworld Forecasts"
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: 14-Day COVID-19 Forecast
      - href: methodology.qmd
        text: Methodology
      - href: about.qmd
        text: About
  repo-url: https://github.com/EpiForeSITE/epiworld-forecasts
  repo-branch: master
  repo-actions: [edit, source, issue]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
