project:
  type: website
  output-dir: "build/html/"

website:
  title: "Epiworld Forecasts"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
