# Name of workflow
name: Run Epiworld Forecast

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches:
      - "main"
      - "8-write-github-action-to-push-quarto-website-to-github-page"
  pull_request:
    branches: [ "main" ]

  # Schedule action to run weekly
  #  at specific UTC times using POSIX cron syntax
  # Set here to run at 6am UTC every Thursday (since
  # DHHS dataset updates weekly on Wednesdays)
  schedule:
    - cron: '0 6 * * 4'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: ghcr.io/epiforesite/epiworld-forecasts

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
